build: config.tex 
	$(MAKE) -C d1/ build
	$(MAKE) -C d2/ build
	$(MAKE) -C d3/ build
	$(MAKE) -C d4/ build
	$(MAKE) -C d5/ build
	$(MAKE) -C d6/ build
	$(MAKE) -C d7/ build
	$(MAKE) -C d8/ build
	$(MAKE) -C d9/ build


clean:
	$(MAKE) -C d1/ clean
	$(MAKE) -C d2/ clean
	$(MAKE) -C d3/ clean
	$(MAKE) -C d4/ clean
	$(MAKE) -C d5/ clean
	$(MAKE) -C d6/ clean
	$(MAKE) -C d7/ clean
	$(MAKE) -C d8/ clean
	$(MAKE) -C d9/ clean
